name: flutter_recruitment_task
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.0

dependencies:
  bloc: 8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: 4.9.0
  json_serializable: 6.8.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: 2.3.3
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.24.9

flutter:
  uses-material-design: true

  assets:
    - assets/mocks/products_pages/1.json
    - assets/mocks/products_pages/2.json
    - assets/mocks/products_pages/3.json
